# Generated by Django 5.0.6 on 2024-07-19 11:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='missingPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('status', models.BooleanField(default=False)),
                ('desc', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='static/images/')),
            ],
        ),
    ]
