# Generated by Django 5.0.6 on 2024-07-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisasterShield', '0002_blood_donation_report_userreputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_donation',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
