# Generated by Django 5.0.6 on 2024-07-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DisasterShield', '0003_blood_donation_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missingperson',
            old_name='status',
            new_name='found',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
